"""pmce_conflicts_metrics"""
from alembic import op
import sqlalchemy as sa

revision = '4d285f6fb97d'
down_revision = 'ad4b47f3975b'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pmce_outbox', sa.Column('superseded_by', sa.Uuid(), nullable=True))
    op.add_column('pmce_outbox', sa.Column('bytes_attempted', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pmce_outbox', sa.Column('bytes_acknowledged', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pmce_outbox', 'bytes_acknowledged')
    op.drop_column('pmce_outbox', 'bytes_attempted')
    op.drop_column('pmce_outbox', 'superseded_by')
    # ### end Alembic commands ###
