"""mission_accountability"""
from alembic import op
import sqlalchemy as sa

revision = '911a743ebba4'
down_revision = 'fabd8eceae1e'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('check_in_interval_minutes', sa.Integer(), server_default='60', nullable=False))
    op.add_column('missions', sa.Column('overdue_grace_minutes', sa.Integer(), server_default='15', nullable=False))
    op.add_column('missions', sa.Column('escalation_level', sa.String(length=30), server_default='none', nullable=False))
    op.add_column('missions', sa.Column('escalation_reason', sa.String(length=500), nullable=True))
    op.add_column('missions', sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'completed_at')
    op.drop_column('missions', 'actual_departure')
    op.drop_column('missions', 'escalation_reason')
    op.drop_column('missions', 'escalation_level')
    op.drop_column('missions', 'overdue_grace_minutes')
    op.drop_column('missions', 'check_in_interval_minutes')
    # ### end Alembic commands ###
