"""file_management"""
from alembic import op
import sqlalchemy as sa

revision = 'aa6528c26a89'
down_revision = '4d285f6fb97d'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('confidentiality', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prepared_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepared_files_file_id'), 'prepared_files', ['file_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prepared_files_file_id'), table_name='prepared_files')
    op.drop_table('prepared_files')
    op.drop_table('managed_files')
    # ### end Alembic commands ###
